version: '3'
services:
  mysql:
    image: 'mysql/mysql-server'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3308:3306
    volumes:
      - ~/datas/report/mysql:/var/lib/mysql
      - ./docker-mysql-initdb:/docker-entrypoint-initdb.d
  web:
    extra_hosts:
      - "xdebug_client_ip:${LOCALADDRESS}"
    command: bash -c 'chmod 777 /root/entrypoints/xdebug/web_entrypoint.sh & /root/entrypoints/xdebug/web_entrypoint.sh & /usr/bin/supervisord -c /etc/docker/supervisord.conf'
    tty: true
    image: 'whitehart/nginx-php-7'
    depends_on:
      - mysql
    ports:
      - 88:80
    volumes:
      - ~/configs/report/nginx:/etc/nginx/conf.d
      - ./:/var/www/html/
      - ~/logs/report/nginx:/var/log/nginx
      - ~/entrypoints/xdebug:/root/entrypoints/xdebug
  adminer:
    image: adminer
    depends_on:
      - mysql
    ports:
      - 9000:8080
  selenium:
      image: selenium/standalone-chrome:latest